/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JPanel;

/**
 *
 * @author alumno
 */
public class Gestor extends javax.swing.JFrame {

    private Panel1a1 pnl1a1;
    private PanelLogin pnlAcceder;
    private PanelTable pnlTable;
    private PanelAcercaDe pnlAcerca;
    private PanelTienda pnlTienda;
    private PanelLibro pnlLibro;
    private PanelTrabajador pnlUsuario;
    
    /**
     * Creates new form Gestor
     */
    public Gestor() {
        pnl1a1 = null;
        pnlAcceder = null;
        pnlTable = null;
        pnlAcerca = null;
        pnlTienda = null;
        pnlLibro = null;
        pnlUsuario = null;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenu = new javax.swing.JMenuBar();
        menuLogin = new javax.swing.JMenu();
        itemAbrir = new javax.swing.JMenuItem();
        itemCerrar = new javax.swing.JMenuItem();
        menuVista = new javax.swing.JMenu();
        item1a1 = new javax.swing.JMenuItem();
        itemTable = new javax.swing.JMenuItem();
        itemUsuario = new javax.swing.JMenuItem();
        itemLibro = new javax.swing.JMenuItem();
        itemTienda = new javax.swing.JMenuItem();
        menuOtro = new javax.swing.JMenu();
        itemModPerfil = new javax.swing.JMenuItem();
        menuAcercaDe = new javax.swing.JMenu();
        itemInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Práctica 6");

        jLabel2.setText("Pedro Puertas Rodríguez");

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(96, 96, 96))))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addGap(53, 53, 53))
        );

        menuLogin.setText("Login");

        itemAbrir.setText("Abrir");
        itemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAbrirActionPerformed(evt);
            }
        });
        menuLogin.add(itemAbrir);

        itemCerrar.setText("Cerrar");
        itemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarActionPerformed(evt);
            }
        });
        menuLogin.add(itemCerrar);
        itemCerrar.setEnabled(false);

        jMenu.add(menuLogin);

        menuVista.setText("Vista");

        item1a1.setText("Ver editoriales");
        item1a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item1a1ActionPerformed(evt);
            }
        });
        menuVista.add(item1a1);

        itemTable.setText("Ver listado libros");
        itemTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTableActionPerformed(evt);
            }
        });
        menuVista.add(itemTable);

        itemUsuario.setText("Ver perfil");
        itemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuarioActionPerformed(evt);
            }
        });
        menuVista.add(itemUsuario);

        itemLibro.setText("Alta/Baja libros");
        itemLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLibroActionPerformed(evt);
            }
        });
        menuVista.add(itemLibro);

        itemTienda.setText("Ver tienda");
        itemTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTiendaActionPerformed(evt);
            }
        });
        menuVista.add(itemTienda);

        jMenu.add(menuVista);
        menuVista.setEnabled(false);

        menuOtro.setText("Otro");

        itemModPerfil.setText("Modificar perfil");
        itemModPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemModPerfilActionPerformed(evt);
            }
        });
        menuOtro.add(itemModPerfil);

        jMenu.add(menuOtro);
        menuOtro.setEnabled(false);

        menuAcercaDe.setText("Acerca de");

        itemInfo.setText("Info");
        itemInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInfoActionPerformed(evt);
            }
        });
        menuAcercaDe.add(itemInfo);

        jMenu.add(menuAcercaDe);
        menuAcercaDe.setEnabled(false);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAbrirActionPerformed
        
        pnlAcceder = new PanelLogin(menuVista, menuOtro, menuAcercaDe, itemAbrir, itemCerrar);
        visualizar(pnlAcceder);
        
    }//GEN-LAST:event_itemAbrirActionPerformed

    private void itemInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInfoActionPerformed
       
        pnlAcerca = new PanelAcercaDe();
        visualizar(pnlAcerca);
        
    }//GEN-LAST:event_itemInfoActionPerformed

    private void item1a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item1a1ActionPerformed
        
        pnl1a1 = new Panel1a1();
        visualizar(pnl1a1);
        
    }//GEN-LAST:event_item1a1ActionPerformed

    private void itemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarActionPerformed
        menuVista.setEnabled(false);
        menuAcercaDe.setEnabled(false);
        menuOtro.setEnabled(false);
        itemCerrar.setEnabled(false);
        itemAbrir.setEnabled(true);
        
        visualizar(jPanelPrincipal);
    }//GEN-LAST:event_itemCerrarActionPerformed

    private void itemTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTableActionPerformed
        pnlTable = new PanelTable();
        visualizar(pnlTable);
    }//GEN-LAST:event_itemTableActionPerformed

    private void itemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuarioActionPerformed
        
        pnlUsuario = new PanelTrabajador(false);
        visualizar(pnlUsuario);
        
    }//GEN-LAST:event_itemUsuarioActionPerformed

    private void itemModPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemModPerfilActionPerformed
        
        pnlUsuario = new PanelTrabajador(true);
        visualizar(pnlUsuario);
        
    }//GEN-LAST:event_itemModPerfilActionPerformed

    private void itemLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLibroActionPerformed
        
        pnlLibro = new PanelLibro();
        visualizar(pnlLibro);
        this.setMinimumSize(pnlLibro.getPreferredSize());
    }//GEN-LAST:event_itemLibroActionPerformed

    private void itemTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTiendaActionPerformed
        
        pnlTienda = new PanelTienda();
        visualizar(pnlTienda);
        
    }//GEN-LAST:event_itemTiendaActionPerformed

    public void visualizar(JPanel panel){
        this.setContentPane(panel);
        pack();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem item1a1;
    private javax.swing.JMenuItem itemAbrir;
    private javax.swing.JMenuItem itemCerrar;
    private javax.swing.JMenuItem itemInfo;
    private javax.swing.JMenuItem itemLibro;
    private javax.swing.JMenuItem itemModPerfil;
    private javax.swing.JMenuItem itemTable;
    private javax.swing.JMenuItem itemTienda;
    private javax.swing.JMenuItem itemUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JMenu menuAcercaDe;
    private javax.swing.JMenu menuLogin;
    private javax.swing.JMenu menuOtro;
    private javax.swing.JMenu menuVista;
    // End of variables declaration//GEN-END:variables
}
