/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.LoginController;
import controlador.MoverController;
import controlador.ProgramExceptions;
import controlador.TablaController;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import modelo.Editorial;
import modelo.Libro;

/**
 *
 * @author alumno
 */
public class Panel1a1 extends javax.swing.JPanel {

    /**
     * Creates new form Panel1a1
     */
    public Panel1a1() {
        initComponents();

        MoverController.iniciar("SELECT * FROM EDITORIAL");
        cargarDatos();
        updateBotones();

    }

    public void updateBotones() {
        try {
            if (MoverController.primero()) {
                btnAnterior.setEnabled(false);
                btnPrimero.setEnabled(false);
            } else {
                btnAnterior.setEnabled(true);
                btnPrimero.setEnabled(true);
            }

            if (MoverController.ultimo()) {
                btnSiguiente.setEnabled(false);
                btnUltimo.setEnabled(false);
            } else {
                btnSiguiente.setEnabled(true);
                btnUltimo.setEnabled(true);
            }
        } catch (ProgramExceptions ex) {
            ex.mostrarError();
        }
    }

    public void cargarDatos() {
        try {
            mostrarEdi(MoverController.getEdi());
        } catch (ProgramExceptions ex) {
            ex.mostrarError();
        }
        rellenarJList();
        updateBotones();
        tfId.setEnabled(false);
        tfNombre.setEnabled(false);
        tfCif.setEnabled(false);
    }

    public void mostrarEdi(Editorial e) {
        tfId.setText("" + e.getId());
        tfNombre.setText(e.getNombre());
        tfCif.setText(e.getCif());
        rellenarJList();
    }

    public void rellenarJList() {

        ArrayList<Libro> lista;

        try {
            lista = TablaController.getLibrosEdi(LoginController.getTrabajador(), MoverController.getEdi());

            DefaultListModel model = new DefaultListModel();

            for (int i = 0; i < lista.size(); i++) {
                model.addElement(lista.get(i).infoLibro());
            }
            this.jList.setModel(model);
        } catch (ProgramExceptions ex) {
            ex.mostrarError();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1a1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnPrimero = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCif = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfCif = new javax.swing.JTextField();

        jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList);

        btnAnterior.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAnterior.setText("←");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setText("→");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnPrimero.setText("|<");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });

        btnUltimo.setText(">|");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        lblId.setText("ID Editorial:");

        lblNombre.setText("Nombre:");

        lblCif.setText("CIF:");

        javax.swing.GroupLayout pnl1a1Layout = new javax.swing.GroupLayout(pnl1a1);
        pnl1a1.setLayout(pnl1a1Layout);
        pnl1a1Layout.setHorizontalGroup(
            pnl1a1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1a1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl1a1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCif)
                    .addComponent(lblId)
                    .addComponent(lblNombre)
                    .addGroup(pnl1a1Layout.createSequentialGroup()
                        .addComponent(btnPrimero)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnterior)))
                .addGroup(pnl1a1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1a1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente)
                        .addGap(18, 18, 18)
                        .addComponent(btnUltimo)
                        .addContainerGap())
                    .addGroup(pnl1a1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(pnl1a1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(tfCif)
                            .addComponent(tfId))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnl1a1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnl1a1Layout.setVerticalGroup(
            pnl1a1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1a1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl1a1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnl1a1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl1a1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCif)
                    .addComponent(tfCif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(pnl1a1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente)
                    .addComponent(btnPrimero)
                    .addComponent(btnUltimo))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1a1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1a1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed

        try {
            MoverController.avanzar();
            mostrarEdi(MoverController.getEdi());
            updateBotones();
        } catch (ProgramExceptions ex) {
            ex.mostrarError();
        }


    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed

        try {
            MoverController.retroceder();
            mostrarEdi(MoverController.getEdi());
            updateBotones();
        } catch (ProgramExceptions ex) {
            ex.mostrarError();
        }


    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed

        try {
            MoverController.irUltimo();
            mostrarEdi(MoverController.getEdi());
            updateBotones();
        } catch (ProgramExceptions ex) {
            ex.mostrarError();
        }


    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed

        try {
            MoverController.irPrimero();
            mostrarEdi(MoverController.getEdi());
            updateBotones();
        } catch (ProgramExceptions ex) {
            ex.mostrarError();
        }


    }//GEN-LAST:event_btnPrimeroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JList<String> jList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCif;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnl1a1;
    private javax.swing.JTextField tfCif;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
