/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.LoginController;
import controlador.MoverController;
import controlador.ProgramExceptions;
import controlador.TablaController;
import controlador.UpdateController;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Editorial;
import modelo.Libro;

/**
 *
 * @author alumno
 */
public class Panel1a1 extends javax.swing.JPanel {

    /**
     * Creates new form Panel1a1
     */
    public Panel1a1() {
        initComponents();

        MoverController.iniciar("SELECT * FROM EDITORIAL");
        cargarDatos();
        updateBotones();

    }

    public void updateBotones() {
        try {
            if (MoverController.primero()) {
                btnAnterior.setEnabled(false);
                btnPrimero.setEnabled(false);
            } else {
                btnAnterior.setEnabled(true);
                btnPrimero.setEnabled(true);
            }

            if (MoverController.ultimo()) {
                btnSiguiente.setEnabled(false);
                btnUltimo.setEnabled(false);
            } else {
                btnSiguiente.setEnabled(true);
                btnUltimo.setEnabled(true);
            }
        } catch (ProgramExceptions ex) {
            ex.mostrarError();
        }
    }

    public void cargarDatos() {
        try {
            mostrarEdi(MoverController.getEdi());
        } catch (ProgramExceptions ex) {
            ex.mostrarError();
        }
        rellenarJList();
        updateBotones();
        tfId.setEnabled(false);
        tfNombre.setEnabled(false);
        tfCif.setEnabled(false);
    }

    public void mostrarEdi(Editorial e) {
        tfId.setText("" + e.getId());
        tfNombre.setText(e.getNombre());
        tfCif.setText(e.getCif());
        rellenarJList();
    }

    public void rellenarJList() {

        ArrayList<Libro> lista;

        try {
            lista = TablaController.getLibrosEdi(LoginController.getTrabajador(), MoverController.getEdi());

            DefaultListModel model = new DefaultListModel();

            for (int i = 0; i < lista.size(); i++) {
                model.addElement(lista.get(i).infoLibro());
            }
            this.jList.setModel(model);
        } catch (ProgramExceptions ex) {
            ex.mostrarError();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl1a1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnPrimero = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCif = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfCif = new javax.swing.JTextField();
        btnModi = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        pnl1a1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList);

        pnl1a1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 12, 353, 105));

        btnAnterior.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAnterior.setText("←");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });
        pnl1a1.add(btnAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 265, -1, -1));

        btnSiguiente.setText("→");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        pnl1a1.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 267, -1, -1));

        btnPrimero.setText("|<");
        btnPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeroActionPerformed(evt);
            }
        });
        pnl1a1.add(btnPrimero, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 267, -1, -1));

        btnUltimo.setText(">|");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });
        pnl1a1.add(btnUltimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 267, -1, -1));

        lblId.setText("ID Editorial:");
        pnl1a1.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 137, -1, -1));

        lblNombre.setText("Nombre:");
        pnl1a1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 175, -1, -1));

        lblCif.setText("CIF:");
        pnl1a1.add(lblCif, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 211, -1, -1));
        pnl1a1.add(tfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 135, 197, -1));
        pnl1a1.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 173, 197, -1));
        pnl1a1.add(tfCif, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 209, 197, -1));

        btnModi.setText("Modificar");
        btnModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModiActionPerformed(evt);
            }
        });
        pnl1a1.add(btnModi, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 267, -1, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnl1a1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, 21));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1a1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1a1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed

        try {
            MoverController.avanzar();
            mostrarEdi(MoverController.getEdi());
            updateBotones();
        } catch (ProgramExceptions ex) {
            ex.mostrarError();
        }


    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed

        try {
            MoverController.retroceder();
            mostrarEdi(MoverController.getEdi());
            updateBotones();
        } catch (ProgramExceptions ex) {
            ex.mostrarError();
        }


    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed

        try {
            MoverController.irUltimo();
            mostrarEdi(MoverController.getEdi());
            updateBotones();
        } catch (ProgramExceptions ex) {
            ex.mostrarError();
        }


    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeroActionPerformed

        try {
            MoverController.irPrimero();
            mostrarEdi(MoverController.getEdi());
            updateBotones();
        } catch (ProgramExceptions ex) {
            ex.mostrarError();
        }


    }//GEN-LAST:event_btnPrimeroActionPerformed

    private void btnModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModiActionPerformed

        try {
            tfCif.setEnabled(true);
            tfNombre.setEnabled(true);
            btnPrimero.setEnabled(false);
            btnSiguiente.setEnabled(false);
            btnAnterior.setEnabled(false);
            btnUltimo.setEnabled(false);
            btnModi.setVisible(false);
            btnGuardar.setVisible(true);
        } catch (ProgramExceptions ex) {
            ex.mostrarError();
        }
    }//GEN-LAST:event_btnModiActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            int id = Integer.parseInt(tfId.getText());

            int filas = UpdateController.updateEditorial(tfCif.getText(),
                    tfNombre.getText(), id);

            JOptionPane.showMessageDialog(null, "Número de filas afectadas: "
                    + filas);

            tfCif.setEnabled(false);
            tfNombre.setEnabled(false);
            btnPrimero.setEnabled(true);
            btnSiguiente.setEnabled(true);
            btnAnterior.setEnabled(true);
            btnUltimo.setEnabled(true);
            btnGuardar.setVisible(false);
            btnModi.setVisible(true);
            MoverController.iniciar("SELECT * FROM EDITORIAL");
            cargarDatos();
            updateBotones();
        } catch (ProgramExceptions ex) {
            ex.mostrarError();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModi;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JList<String> jList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCif;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnl1a1;
    private javax.swing.JTextField tfCif;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
