/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.aeat.valida.Validador;
import controlador.LoginController;
import controlador.ProgramExceptions;
import controlador.TablaController;
import controlador.UpdateController;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modelo.Tienda;
import modelo.Trabajador;

/**
 *
 * @author alumno
 */
public class PanelTrabajador extends javax.swing.JPanel {

    private boolean modificar;
    private static String foto = null;

    /**
     * Creates new form PanelTrabajador
     */
    public PanelTrabajador(boolean modificar) {

        this.modificar = modificar;

        initComponents();

        comprobarBotones();
        cargarDatos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTrabajador = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblSalario = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        lblApe = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        dcFecha = new com.toedter.calendar.JDateChooser();
        btnFoto = new javax.swing.JButton();
        lblTienda = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfApe = new javax.swing.JTextField();
        tfSalario = new javax.swing.JTextField();
        tfDni = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        cbTienda = new javax.swing.JComboBox<>();

        pnlTrabajador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setText("Nombre:");
        pnlTrabajador.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 35, -1, -1));

        lblSalario.setText("Salario:");
        pnlTrabajador.add(lblSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 109, -1, -1));

        lblFoto.setText("FOTO");
        pnlTrabajador.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 12, 170, 166));

        lblApe.setText("Apellidos:");
        pnlTrabajador.add(lblApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 72, -1, -1));

        lblDni.setText("DNI:");
        pnlTrabajador.add(lblDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 146, -1, -1));

        lblFecha.setText("Contratación:");
        pnlTrabajador.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 185, -1, -1));
        pnlTrabajador.add(dcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 181, 249, -1));

        btnFoto.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnFoto.setText("Cambiar foto");
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });
        pnlTrabajador.add(btnFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 218, -1, -1));

        lblTienda.setText("ID Tienda:");
        pnlTrabajador.add(lblTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 221, -1, -1));
        pnlTrabajador.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 33, 249, -1));
        pnlTrabajador.add(tfApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 70, 249, -1));
        pnlTrabajador.add(tfSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 107, 249, -1));
        pnlTrabajador.add(tfDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 144, 249, -1));

        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btnGuardar.setText("Guardar cambios");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlTrabajador.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        cbTienda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlTrabajador.add(cbTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed

        try {

            Path origen;
            Path destino;

            JFileChooser fcFoto = new JFileChooser();
            fcFoto.showSaveDialog(null);

            int returnVal = fcFoto.showOpenDialog(null);

            File f = fcFoto.getSelectedFile();

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                try {
                    origen = Paths.get(f.getPath());
                    destino = Paths.get(System.getProperty("user.dir") + "/src/fotos/"
                            + f.getName());
                    Files.copy(origen, destino, REPLACE_EXISTING);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Error al guardar la foto");
                }

                foto = f.getName();

                System.out.println(foto);

                Image img = new ImageIcon(System.getProperty("user.dir")
                        + "/src/fotos/" + f.getName()).getImage();

                ImageIcon ic = new ImageIcon(img.getScaledInstance(170, 166, Image.SCALE_SMOOTH));

                lblFoto.setIcon(ic);

                btnFoto.setVisible(true);
                btnGuardar.setVisible(true);
                tfDni.setVisible(true);
                tfNombre.setVisible(true);
                tfApe.setVisible(true);
                tfSalario.setVisible(true);
                cbTienda.setVisible(true);
                lblApe.setVisible(true);
                lblDni.setVisible(true);
                lblFoto.setVisible(true);
                lblNombre.setVisible(true);
                lblSalario.setVisible(true);
                lblTienda.setVisible(true);
                lblFecha.setVisible(true);
                dcFecha.setVisible(true);

                fcFoto.setVisible(false);
            } else {
                throw new ProgramExceptions(11);
            }

        } catch (ProgramExceptions ex) {
            ex.mostrarError();
        }

    }//GEN-LAST:event_btnFotoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        try {

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            int filas;
            String dni, fecha;

            Validador val = new Validador();
            dni = tfDni.getText();

            fecha = sdf.format(dcFecha.getDate());

            if (val.checkNif(dni) < 0) {
                throw new ProgramExceptions(9);
            } else {
                if (foto == null) {
                    filas = UpdateController.updateTrabajadorSinF(dni, fecha,
                            LoginController.getTrabajador().getId());
                } else {
                    filas = UpdateController.updateTrabajador(foto, dni, fecha,
                            LoginController.getTrabajador().getId());
                }

                JOptionPane.showMessageDialog(null, "Filas afectadas: " + filas);

            }

            LoginController.actTrabajador();

        } catch (ProgramExceptions ex) {
            ex.mostrarError();
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    public void comprobarBotones() {

        if (modificar) {
            btnFoto.setVisible(true);
            btnGuardar.setVisible(true);
            tfDni.setEnabled(true);
            tfNombre.setEnabled(false);
            tfApe.setEnabled(false);
            tfSalario.setEnabled(false);
            cbTienda.setEnabled(false);
            dcFecha.setEnabled(true);
        } else {
            btnFoto.setVisible(false);
            btnGuardar.setVisible(false);
            tfDni.setEnabled(false);
            tfNombre.setEnabled(false);
            tfApe.setEnabled(false);
            tfSalario.setEnabled(false);
            cbTienda.setEnabled(false);
            dcFecha.setEnabled(false);
        }

    }

    private void cargarDatos() {

        try {

            ArrayList<Tienda> listaTienda = new ArrayList<Tienda>();
            listaTienda = TablaController.getTiendas();
            String[] tiendas = new String[(listaTienda.size())];

            Trabajador t = LoginController.getTrabajador();

            Image img = new ImageIcon(System.getProperty("user.dir")
                    + "/src/fotos/" + t.getFoto()).getImage();

            ImageIcon ic = new ImageIcon(img.getScaledInstance(170, 166, Image.SCALE_SMOOTH));

            for (int i = 0; i < tiendas.length; i++) {
                tiendas[i] = listaTienda.get(i).getDireccion();
            }

            DefaultComboBoxModel<String> cbT = new DefaultComboBoxModel(tiendas);

            cbTienda.setModel(cbT);

            tfDni.setText(t.getDni());
            tfNombre.setText(t.getNombre());
            tfApe.setText(t.getApellidos());
            tfSalario.setText("" + t.getSalario());
            lblFoto.setIcon(ic);
            dcFecha.setCalendar(t.getFechaCont());
            cbTienda.setSelectedIndex(t.getTienda());

        } catch (ProgramExceptions ex) {
            ex.mostrarError();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbTienda;
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JLabel lblApe;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblTienda;
    private javax.swing.JPanel pnlTrabajador;
    private javax.swing.JTextField tfApe;
    private javax.swing.JTextField tfDni;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfSalario;
    // End of variables declaration//GEN-END:variables
}
